//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.19 at 12:55:27 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webservices.river.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.river.webservices;
